import {ArrayBindingElement, LiteralTypeNode, ParenthesizedTypeNode, TupleTypeNode, UnionTypeNode, IntersectionTypeNode, ArrayTypeNode, ArrayBindingPattern, IndexedAccessTypeNode, TypeOperatorNode, BindingElement, BindingName, ComputedPropertyName, Decorator, EntityName, Expression, ExpressionWithTypeArguments, FunctionTypeNode, HeritageClause, Identifier, KeywordTypeNode, MappedTypeNode, Modifier, NodeArray, NumericLiteral, ObjectBindingPattern, OmittedExpression, ParameterDeclaration, PropertyName, PropertySignature, QualifiedName, StringLiteral, SyntaxKind, Token, TypeElement, TypeLiteralNode, TypeNode, TypeParameterDeclaration, TypeReferenceNode} from "typescript";
import {LastTypeNode} from "@wessberg/typescript-ast-util";

export interface ICopier {
	copyType (type: TypeNode): TypeNode;
	copyNumericLiteral (type: NumericLiteral): NumericLiteral;
	copyParenthesizedType (type: ParenthesizedTypeNode): ParenthesizedTypeNode;
	copyTupleTypeNode (type: TupleTypeNode): TupleTypeNode;
	copyLiteralTypeNode (type: LiteralTypeNode): LiteralTypeNode;
	copyTypeOperatorNode (type: TypeOperatorNode): TypeOperatorNode;
	copyIndexedAccessTypeNode (type: IndexedAccessTypeNode): IndexedAccessTypeNode;
	copyTypeReferenceNode (type: TypeReferenceNode): TypeReferenceNode;
	copyMappedTypeNode (type: MappedTypeNode): MappedTypeNode;
	copyFunctionTypeNode (type: FunctionTypeNode): FunctionTypeNode;
	copyParameter (type: ParameterDeclaration): ParameterDeclaration;
	copyArrayBindingPattern (type: ArrayBindingPattern): ArrayBindingPattern;
	copyObjectBindingPattern (type: ObjectBindingPattern): ObjectBindingPattern;
	copyBindingElement (type: BindingElement): BindingElement;
	copyUnionTypeNode (type: UnionTypeNode): UnionTypeNode;
	copyIntersectionTypeNode (type: IntersectionTypeNode): IntersectionTypeNode;
	copyArrayTypeNode (type: ArrayTypeNode): ArrayTypeNode;
	copyBindingElements (type: NodeArray<BindingElement>): NodeArray<BindingElement>;
	copyOmittedExpression (): OmittedExpression;
	copyArrayBindingElement (type: ArrayBindingElement): ArrayBindingElement;
	copyArrayBindingElements (type: NodeArray<ArrayBindingElement>): NodeArray<ArrayBindingElement>;
	copyBindingName (type: BindingName): BindingName;
	copyDecorator (type: Decorator): Decorator;
	copyDecorators (type: NodeArray<Decorator>): NodeArray<Decorator>;
	copyLastTypeNode (type: LastTypeNode): LastTypeNode;
	createLastTypeNode (literal: Identifier): LastTypeNode;
	copyKeywordTypeNode (type: KeywordTypeNode): KeywordTypeNode;
	copyTypeLiteralNode (type: TypeLiteralNode): TypeLiteralNode;
	copyPropertyName (type: PropertyName): PropertyName;
	copyComputedPropertyName (type: ComputedPropertyName): ComputedPropertyName;
	copyStringLiteral (type: StringLiteral): StringLiteral;
	copyTypeElement (type: TypeElement): TypeElement;
	copyPropertySignature (type: PropertySignature): PropertySignature;
	copyTypeParameterDeclarations (type: NodeArray<TypeParameterDeclaration>): NodeArray<TypeParameterDeclaration>;
	copyTypeParameterDeclaration (type: TypeParameterDeclaration): TypeParameterDeclaration;
	copyTypeArguments (type: NodeArray<TypeNode>): NodeArray<TypeNode>;
	copyHeritageClauses (type: NodeArray<HeritageClause>): NodeArray<HeritageClause>;
	copyHeritageClause (type: HeritageClause): HeritageClause;
	copyModifiers (type: NodeArray<Modifier>): NodeArray<Modifier>;
	copyModifier (type: Modifier): Modifier;
	copyExpression (type: Expression): Expression;
	copyIdentifier (type: Identifier): Identifier;
	copyEntityName (type: EntityName): EntityName;
	copyQualifiedName (type: QualifiedName): QualifiedName;
	copyToken<TKind extends SyntaxKind> (type: Token<TKind>): Token<TKind>;
	copyExpressionsWithTypeArguments (type: NodeArray<ExpressionWithTypeArguments>): NodeArray<ExpressionWithTypeArguments>;
	copyExpressionWithTypeArguments (type: ExpressionWithTypeArguments): ExpressionWithTypeArguments;
}